import { mkdirSync, writeFileSync, existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { CLI_ROOT } from './paths.mjs';
import { composeTokensCss } from '../runtime/lib/composeTokens.mjs';

/**
 * Workspace root, derived from packages/cli/. The unified root `.env` lives
 * here and holds shared FIREBASE_*, NEBULA_*, FIRESTORE_* values consumed by
 * Platform, the legacy docs site, AND the CLI runtime.
 */
const WORKSPACE_ROOT = resolve(CLI_ROOT, '..', '..');

/**
 * Load the workspace root `.env` into `process.env`. Uses Node 20.12+'s
 * built-in `process.loadEnvFile` (Node ≥22 is pinned by `.nvmrc`). Existing
 * env vars take precedence — shell exports and CI secrets win over .env.
 */
function loadRootEnv() {
  const envPath = resolve(WORKSPACE_ROOT, '.env');
  if (!existsSync(envPath)) return;
  try {
    process.loadEnvFile(envPath);
  } catch (err) {
    // Surface but don't crash — analytics will simply skip bootstrap if the
    // FIREBASE_* values aren't there.
    process.stderr.write(
      `[nebula] could not load root .env: ${err && err.message ? err.message : String(err)}\n`,
    );
  }
}

/**
 * Run before any Astro entry point. Sets the env vars that the Astro config
 * + content collection rely on, and writes the composed tokens.css to
 * `packages/cli/.nebula/tokens.css` so the global stylesheet can `@import` it.
 */
export async function prepareAstroEnv({ tenant }) {
  loadRootEnv();
  process.env.NEBULA_TENANT_ROOT = tenant;

  const docsJsonPath = resolve(tenant, 'docs.json');
  const docs = JSON.parse(readFileSync(docsJsonPath, 'utf8'));
  process.env.NEBULA_TENANT_NAME = String(docs.name ?? 'Nebula Docs');

  const themeJsonPath = resolve(tenant, 'theme.json');
  const themeOverrides = existsSync(themeJsonPath)
    ? JSON.parse(readFileSync(themeJsonPath, 'utf8'))
    : null;

  // Surface the tenant's Shiki theme picks to astro.config.mjs via env
  // vars. Both are optional — astro.config falls back to the renderer's
  // defaults (github-light / github-dark) when unset. Driven by the
  // editor's Visual Branding > "Code block — light/dark theme" selects.
  const cbLight = themeOverrides?.codeBlock?.light;
  const cbDark = themeOverrides?.codeBlock?.dark;
  if (typeof cbLight === 'string' && cbLight)
    process.env.NEBULA_SHIKI_LIGHT = cbLight;
  if (typeof cbDark === 'string' && cbDark)
    process.env.NEBULA_SHIKI_DARK = cbDark;

  const baseId = docs.theme?.base ?? themeOverrides?.extends ?? 'mcoe-default';
  const css = await composeTokensCss({ baseId, overrides: themeOverrides });

  const generatedDir = resolve(CLI_ROOT, '.nebula');
  mkdirSync(generatedDir, { recursive: true });
  writeFileSync(resolve(generatedDir, 'tokens.css'), css);

  // Emit analytics config — read by the runtime bootstrap script in
  // DocsLayout.astro. Tenants opt in via `docs.json.analytics`; the actual
  // Firebase keys come from the workspace root `.env`. When the tenant
  // hasn't opted in, the file exports `null` and the bootstrap is a no-op.
  const analyticsConfig = resolveAnalyticsConfig(docs);
  writeFileSync(
    resolve(generatedDir, 'analyticsConfig.mjs'),
    `// generated by prepareAstro.mjs — do not edit by hand\n` +
      `export default ${JSON.stringify(analyticsConfig, null, 2)};\n`,
  );
}

/**
 * Build the runtime analytics config from `docs.json.analytics` + the
 * FIREBASE_* env vars. Returns `null` when the tenant has no analytics
 * block, or when the chosen provider is configured but the env is missing
 * a required value (so we never bootstrap a half-configured Firebase app).
 */
function resolveAnalyticsConfig(docs) {
  const cfg = docs.analytics;
  if (!cfg || cfg.provider !== 'firebase') return null;

  // Map of Firebase SDK config keys to the workspace .env var that supplies
  // each. The env var names match what `products/docs/docusaurus.config.ts`
  // uses, so a single root `.env` serves both runners.
  const FIREBASE_ENV_KEYS = [
    ['apiKey', 'FIREBASE_API_KEY'],
    ['authDomain', 'FIREBASE_AUTH_DOMAIN'],
    ['projectId', 'FIREBASE_PROJECT_ID'],
    ['storageBucket', 'FIREBASE_STORAGE_BUCKET'],
    ['messagingSenderId', 'FIREBASE_MESSAGE_SENDER_ID'],
    ['appId', 'FIREBASE_APP_ID'],
    ['measurementId', 'FIREBASE_MEASUREMENT_ID'],
  ];

  const firebaseConfig = {};
  for (const [key, envName] of FIREBASE_ENV_KEYS) {
    const value = process.env[envName];
    if (!value) {
      process.stderr.write(
        `[nebula] analytics opt-in present but ${envName} is unset; skipping bootstrap\n`,
      );
      return null;
    }
    firebaseConfig[key] = value;
  }

  return {
    provider: 'firebase',
    environment:
      process.env.NEBULA_ENV === 'prod' || process.env.NODE_ENV === 'production'
        ? 'production'
        : 'development',
    firebaseConfig,
  };
}
