import {
  AlignLeft,
  ExternalLink,
  EyeOff,
  Image as ImageIcon,
  Layers,
  Link as LinkIcon,
  PanelLeft,
  Tag,
  Type,
} from 'lucide-react';
import type { IconValue } from '@/components/IconField';
import { SelectRow, TextRow, ToggleRow } from './FormRow';
import { IconRow } from './IconRow';
import { KeywordsRow } from './KeywordsRow';

/**
 * Page frontmatter values surfaced by the editor's settings panel. Mirrors
 * the field set Mintlify exposes in its dashboard (title, slug, external
 * URL, description, icon, sidebar title, OG image, tag, hidden, keywords,
 * mode). Other Mintlify-supported frontmatter keys (`noindex`, `boost`,
 * `deprecated`, `groups`, `iconType`, `hideFooterPagination`,
 * `hideApiMarker`, `timestamp`) round-trip silently — if a tenant authored
 * them by hand they survive a save, but the form doesn't surface them.
 */
export interface PageFrontmatterValues {
  title: string;
  description: string;
  sidebarTitle: string;
  icon: IconValue;
  tag: string;
  hidden: boolean;
  mode: string;
  url: string;
  keywords: string[];
  ogImage: string;
}

interface PageSettingsFormProps {
  slug: string;
  values: PageFrontmatterValues;
  onChange: (patch: Partial<PageFrontmatterValues>) => void;
}

const MODE_OPTIONS = [
  { value: 'default', label: 'Default' },
  { value: 'custom', label: 'Custom' },
] as const;

/**
 * Page settings form — every field writes to the MDX frontmatter via the
 * parent's `onChange` callback. The slug is read-only because renaming an
 * MDX file is a separate operation (file move + nav update).
 */
export function PageSettingsForm({
  slug,
  values,
  onChange,
}: PageSettingsFormProps) {
  const tagEnabled = values.tag.length > 0;

  return (
    <div className="flex flex-col gap-5">
      <TextRow
        label="Title"
        icon={Type}
        value={values.title}
        onChange={(v) => onChange({ title: v })}
        placeholder="Page title"
      />
      <TextRow
        label="Slug"
        icon={LinkIcon}
        value={slug}
        onChange={() => undefined}
        placeholder="path/to/page"
      />
      <TextRow
        label="External URL"
        icon={ExternalLink}
        type="url"
        value={values.url}
        onChange={(v) => onChange({ url: v })}
        placeholder="Enter external url"
      />
      <TextRow
        label="Description"
        icon={AlignLeft}
        value={values.description}
        onChange={(v) => onChange({ description: v })}
        placeholder="Enter description"
      />
      <IconRow
        value={values.icon}
        onChange={(v) => onChange({ icon: v })}
      />
      <TextRow
        label="Sidebar title"
        icon={PanelLeft}
        value={values.sidebarTitle}
        onChange={(v) => onChange({ sidebarTitle: v })}
        placeholder="Enter sidebar title"
      />
      <TextRow
        label="OG Image URL"
        icon={ImageIcon}
        type="url"
        value={values.ogImage}
        onChange={(v) => onChange({ ogImage: v })}
        placeholder="Enter URL (Auto generated by default)"
      />
      <ToggleRow
        label="Tag"
        icon={Tag}
        checked={tagEnabled}
        onChange={(v) => onChange({ tag: v ? values.tag || ' ' : '' })}
      />
      {tagEnabled ? (
        <TextRow
          label="Tag value"
          icon={Tag}
          value={values.tag}
          onChange={(v) => onChange({ tag: v })}
          placeholder="NEW, BETA, …"
        />
      ) : null}
      <ToggleRow
        label="Hidden"
        icon={EyeOff}
        checked={values.hidden}
        onChange={(v) => onChange({ hidden: v })}
        labels={['Yes', 'No']}
      />
      <KeywordsRow
        value={values.keywords}
        onChange={(v) => onChange({ keywords: v })}
      />
      <SelectRow
        label="Mode"
        icon={Layers}
        value={values.mode}
        onChange={(v) => onChange({ mode: v })}
        options={MODE_OPTIONS}
        placeholder="Default"
      />
    </div>
  );
}
