import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

export function autoSidebar(name: string): SidebarsConfig {
  return {
    [`${name}Sidebar`]: [{ type: "autogenerated", dirName: "." }],
  };
}
