// Runtime entry point loaded by `DocsLayout.astro`'s `<script>` tag on
// every page. Astro/Vite bundles this and inlines the imported config so
// the browser receives a single hydrated module.

import { firePageView, installAutoTracker } from '@nebula-docs/analytics';
import { bootstrapFirebase } from '@nebula-docs/analytics/firebase';
// Generated by `prepareAstro.mjs` — exports `null` when the tenant has not
// opted into analytics, otherwise a resolved provider config.
import analyticsConfig from '../../../.nebula/analyticsConfig.mjs';

if (typeof window !== 'undefined' && analyticsConfig) {
  if (analyticsConfig.provider === 'firebase') {
    bootstrapFirebase({
      firebaseConfig: analyticsConfig.firebaseConfig,
      environment: analyticsConfig.environment,
    });
  }

  installAutoTracker();
  firePageView(window.location.pathname, document.title);
}
